{
  "description": "Get local failed validation",
  "environment": [
    {
      "type": "device",
      "label": "phone"
    }
  ],
  "driver": {
    "type": "DeviceTest",
    "py_file": [
      "testcases/level0/case03_get001.py"
    ]
  }
}